@startuml


component Unity as unity

cloud cloud {
    component "Game server" as gameserver
    component Dashboard as dashboard
    unity <-down-> gameserver
    gameserver <-left-> dashboard
}

node desktop {
    component OpenCV as opencv
    component Camera as camera
    camera -> opencv
}

opencv -down-> gameserver

node labyrinth {
    component Esp32 as esp32
    component Highscore as highscore
    esp32 --> highscore
    component Microphone as microphone
    microphone --> esp32
    component "IR Sensor" as irsensor
    irsensor --> esp32
    component "Motors" as motors
    esp32 --> motors
    component "Gyroscope" as gyro
    gyro --> esp32
    component "Joystick" as joystick
    joystick --> esp32

}

gameserver <-left-> esp32

@enduml