/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "./GameMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Vec2, Vec2, AUTO)


PB_BIND(JoystickState, JoystickState, AUTO)


PB_BIND(BallState, BallState, AUTO)


PB_BIND(BoardState, BoardState, AUTO)



